### ISSUE TITLE
hhvm-9999 requires binutils[static-libs]

### ISSUE THREAD

**Issue by s9e** [javer/gentoo-overlay#18]
About a week ago HHVM stopped compiling and started complaining that I needed to install binutils. Recompiling binutils with the static-libs USE flag fixed that issue.

Judging by the comments in https://github.com/facebook/hhvm/commit/d7a95c828395a024c76a887a6e5285729055a43d it now requires libbfd to be compiled as a static lib, meaning that it now depends on binutils with the static-libs USE flag.

**Comment by javer** [comment]
Fixed in 564f27ca408ddbf827d73f4f08914953b1c53b37
