### ISSUE TITLE
dev-php/hhvm version bump: 3.6.2 and 3.7.0

### ISSUE THREAD

**Issue by devurandom** [javer/gentoo-overlay#24]
Versions 3.6.2 and 3.7.0 of HHVM have been released. See [the 3.7.0 release announcement](http://hhvm.com/blog/9059/hhvm-3-7-0) and [the 3.6.2 tag](https://github.com/facebook/hhvm/releases/tag/HHVM-3.6.2).

**Comment by javer** [comment]
Done in 34eeb8897d422a36c403548c48950ee12ca2dd70.
